export type Gira = {
  titulo: string;
  day: number;
  month: string;
  year: number;
  monthIndex: number;
  exibirNoHero: boolean;
};

export const giras: Array<Gira> = [
  {
    titulo: "Gira com Pretos Velhos",
    day: 3,
    month: "Junho",
    year: 2025,
    monthIndex: 6,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Exus e Pomba Giras",
    day: 10,
    month: "Junho",
    year: 2025,
    monthIndex: 6,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Caboclos e Boiadeiros",
    day: 17,
    month: "Junho",
    year: 2025,
    monthIndex: 6,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Caboclos / Dia de Xangô",
    day: 24,
    month: "Junho",
    year: 2025,
    monthIndex: 6,
    exibirNoHero: true,
  },
  {
    titulo: "Aniversário de 1 Ano do Centro",
    day: 1,
    month: "Julho",
    year: 2025,
    monthIndex: 7,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Pretos Velhos",
    day: 8,
    month: "Julho",
    year: 2025,
    monthIndex: 7,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Caboclos e Boiadeiros",
    day: 15,
    year: 2025,
    month: "Julho",
    monthIndex: 7,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Pretos Velhos",
    day: 22,
    year: 2025,
    month: "Julho",
    monthIndex: 7,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Caboclos",
    day: 29,
    year: 2025,
    month: "Julho",
    monthIndex: 7,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Exus e Pomba Giras",
    day: 5,
    month: "Agosto",
    year: 2025,
    monthIndex: 8,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Caboclos e Boiadeiros",
    day: 12,
    month: "Agosto",
    year: 2025,
    monthIndex: 8,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Caboclos",
    day: 19,
    month: "Agosto",
    year: 2025,
    monthIndex: 8,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Pretos Velhos",
    day: 26,
    month: "Agosto",
    year: 2025,
    monthIndex: 8,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Exus e Pomba Giras",
    day: 2,
    month: "Setembro",
    year: 2025,
    monthIndex: 9,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Pretos Velhos",
    day: 9,
    month: "Setembro",
    year: 2025,
    monthIndex: 9,
    exibirNoHero: true,
  },
  {
    titulo: "Não haverá Gira",
    day: 16,
    month: "Setembro",
    year: 2025,
    monthIndex: 9,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Erês",
    day: 23,
    month: "Setembro",
    year: 2025,
    monthIndex: 9,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Caboclos",
    day: 30,
    month: "Setembro",
    year: 2025,
    monthIndex: 9,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Exus e Pomba Giras",
    day: 7,
    month: "Outubro",
    year: 2025,
    monthIndex: 10,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Pretos Velhos",
    day: 14,
    month: "Outubro",
    year: 2025,
    monthIndex: 10,
    exibirNoHero: true,
  },
  {
    titulo: "Não haverá Gira",
    day: 21,
    month: "Outubro",
    year: 2025,
    monthIndex: 10,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Caboclos e Boiadeiros",
    day: 28,
    month: "Outubro",
    year: 2025,
    monthIndex: 10,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Pretos Velhos",
    day: 4,
    month: "Novembro",
    year: 2025,
    monthIndex: 11,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Caboclos",
    day: 11,
    month: "Novembro",
    year: 2025,
    monthIndex: 11,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Caboclos e Boiadeiros",
    day: 18,
    month: "Novembro",
    year: 2025,
    monthIndex: 11,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Exus e Pomba Giras",
    day: 25,
    month: "Novembro",
    year: 2025,
    monthIndex: 11,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Exus e Pomba Giras",
    day: 2,
    month: "Dezembro",
    year: 2025,
    monthIndex: 12,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Pretos Velhos",
    day: 9,
    month: "Dezembro",
    year: 2025,
    monthIndex: 12,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Exus e Pomba Giras",
    day: 16,
    month: "Dezembro",
    year: 2025,
    monthIndex: 12,
    exibirNoHero: true,
  },
  {
    titulo: "Recesso",
    day: 23,
    month: "Dezembro",
    year: 2025,
    monthIndex: 12,
    exibirNoHero: true,
  },
  {
    titulo: "Recesso",
    day: 30,
    month: "Dezembro",
    year: 2025,
    monthIndex: 12,
    exibirNoHero: true,
  },
  {
    titulo: "Desenvolvimento/Estudos (apenas para membros da casa)",
    day: 15,
    month: "Janeiro",
    year: 2026,
    monthIndex: 1,
    exibirNoHero: false,
  },
  {
    titulo: "Gira com Caboclos / OXÓSSI",
    day: 20,
    month: "Janeiro",
    year: 2026,
    monthIndex: 1,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Caboclos e Boiadeiros",
    day: 27,
    month: "Janeiro",
    year: 2026,
    monthIndex: 1,
    exibirNoHero: true,
  },
  {
    titulo: "Desenvolvimento/Estudos (apenas para membros da casa)",
    day: 29,
    month: "Janeiro",
    year: 2026,
    monthIndex: 1,
    exibirNoHero: false,
  },
  {
    titulo: "Gira com Exus e Pomba Giras",
    day: 3,
    month: "Fevereiro",
    year: 2026,
    monthIndex: 2,
    exibirNoHero: true,
  },
  {
    titulo: "Gira com Pretos Velhos",
    day: 10,
    month: "Fevereiro",
    year: 2026,
    monthIndex: 2,
    exibirNoHero: true,
  },
  {
    titulo: "Desenvolvimento/Estudos (apenas para membros da casa)",
    day: 19,
    month: "Fevereiro",
    year: 2026,
    monthIndex: 2,
    exibirNoHero: false,
  },
  {
    titulo: "Gira com Caboclos",
    day: 24,
    month: "Fevereiro",
    year: 2026,
    monthIndex: 2,
    exibirNoHero: true,
  },
  {
    titulo: "Desenvolvimento/Estudos (apenas para membros da casa)",
    day: 26,
    month: "Fevereiro",
    year: 2026,
    monthIndex: 2,
    exibirNoHero: false,
  },
];
