export type Gira = {
  titulo: string;
  day: number;
  month: string;
  year: number;
  monthIndex: number;
};

export const giras: Array<Gira> = [
  {
    titulo: "Gira com Pretos Velhos",
    day: 3,
    month: "Junho",
    year: 2025,
    monthIndex: 6,
  },
  {
    titulo: "Gira com Exus e Pomba Giras",
    day: 10,
    month: "Junho",
    year: 2025,
    monthIndex: 6,
  },
  {
    titulo: "Gira com Caboclos e Boiadeiros",
    day: 17,
    month: "Junho",
    year: 2025,
    monthIndex: 6,
  },
  {
    titulo: "Gira com Caboclos / Dia de Xangô",
    day: 24,
    month: "Junho",
    year: 2025,
    monthIndex: 6,
  },
  {
    titulo: "Aniversário de 1 Ano do Centro",
    day: 1,
    month: "Julho",
    year: 2025,
    monthIndex: 7,
  },
  {
    titulo: "Gira com Pretos Velhos",
    day: 8,
    month: "Julho",
    year: 2025,
    monthIndex: 7,
  },
  {
    titulo: "Gira com Caboclos e Boiadeiros",
    day: 15,
    year: 2025,
    month: "Julho",
    monthIndex: 7,
  },
  {
    titulo: "Gira com Pretos Velhos",
    day: 22,
    year: 2025,
    month: "Julho",
    monthIndex: 7,
  },
  {
    titulo: "Gira com Caboclos",
    day: 29,
    year: 2025,
    month: "Julho",
    monthIndex: 7,
  },
  {
    titulo: "Gira com Exus e Pomba Giras",
    day: 5,
    month: "Agosto",
    year: 2025,
    monthIndex: 8,
  },
  {
    titulo: "Gira com Caboclos e Boiadeiros",
    day: 12,
    month: "Agosto",
    year: 2025,
    monthIndex: 8,
  },
  {
    titulo: "Gira com Caboclos",
    day: 19,
    month: "Agosto",
    year: 2025,
    monthIndex: 8,
  },
  {
    titulo: "Gira com Pretos Velhos",
    day: 26,
    month: "Agosto",
    year: 2025,
    monthIndex: 8,
  },
  {
    titulo: "Gira com Exus e Pomba Giras",
    day: 2,
    month: "Setembro",
    year: 2025,
    monthIndex: 9,
  },
  {
    titulo: "Gira com Pretos Velhos",
    day: 9,
    month: "Setembro",
    year: 2025,
    monthIndex: 9,
  },
  {
    titulo: "Não haverá Gira",
    day: 16,
    month: "Setembro",
    year: 2025,
    monthIndex: 9,
  },
  {
    titulo: "Gira com Erês",
    day: 23,
    month: "Setembro",
    year: 2025,
    monthIndex: 9,
  },
  {
    titulo: "Gira com Caboclos",
    day: 30,
    month: "Setembro",
    year: 2025,
    monthIndex: 9,
  },
  {
    titulo: "Gira com Exus e Pomba Giras",
    day: 7,
    month: "Outubro",
    year: 2025,
    monthIndex: 10,
  },
  {
    titulo: "Gira com Pretos Velhos",
    day: 14,
    month: "Outubro",
    year: 2025,
    monthIndex: 10,
  },
  {
    titulo: "Não haverá Gira",
    day: 21,
    month: "Outubro",
    year: 2025,
    monthIndex: 10,
  },
  {
    titulo: "Gira com Caboclos e Boiadeiros",
    day: 28,
    month: "Outubro",
    year: 2025,
    monthIndex: 10,
  },
  {
    titulo: "Gira com Pretos Velhos",
    day: 4,
    month: "Novembro",
    year: 2025,
    monthIndex: 11,
  },
  {
    titulo: "Gira com Caboclos",
    day: 11,
    month: "Novembro",
    year: 2025,
    monthIndex: 11,
  },
  {
    titulo: "Gira com Caboclos e Boiadeiros",
    day: 18,
    month: "Novembro",
    year: 2025,
    monthIndex: 11,
  },
  {
    titulo: "Gira com Exus e Pomba Giras",
    day: 25,
    month: "Novembro",
    year: 2025,
    monthIndex: 11,
  },
  {
    titulo: "Gira com Exus e Pomba Giras",
    day: 2,
    month: "Dezembro",
    year: 2025,
    monthIndex: 12,
  },
  {
    titulo: "Gira com Pretos Velhos",
    day: 9,
    month: "Dezembro",
    year: 2025,
    monthIndex: 12,
  },
  {
    titulo: "Gira com Exus e Pomba Giras",
    day: 16,
    month: "Dezembro",
    year: 2025,
    monthIndex: 12,
  },
  {
    titulo: "Recesso",
    day: 23,
    month: "Dezembro",
    year: 2025,
    monthIndex: 12,
  },
  {
    titulo: "Recesso",
    day: 30,
    month: "Dezembro",
    year: 2025,
    monthIndex: 12,
  },
];
